# .github/workflows/demo.yml

name: Demo Workflows

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build
        needs: [Development]
        steps:
            - uses: actions/checkout@v4
            - name: Build and deploy on Cloud
              run: npm install

    dev:
        runs-on: ubuntu-latest
        name: Development
        steps:
            - uses: actions/checkout@v4
            - name: Run the developer
              run: npm test  

    Test:
        runs-on: ubuntu-latest
        needs: [build, dev]
        name: Testing
        steps:
            - uses: actions/checkout@v4
            - name: Testing the application
              run: echo test