# .github/workflows/
name: issue
on: 
    issues:
        types: [opened, edited, milestoned]
    pull_request:
        types:
            - opened
        branches:
            -  "releases/**"
jobs:
    build:
      - name: Builds
        run-on: ubuntu-latest
         steps:
            - name: Build and deploy on Cloud                 